---
name: Validate terraform

on:
  push:
    paths:
      - '**/*.tf'
      - '.github/workflows/validate-terraform.yml'
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/validate-terraform.yml'

jobs:
  validate-terraform:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        terraform-version:
          - 0.13.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Terraform init
        run: terraform init
      - name: Terraform format
        run: terraform fmt -check
      - name: Terraform validate
        run: terraform validate
